INSERT INTO TABLE_1S (ID) VALUES (?)

INSERT INTO TABLE_2S (ID, TABLE_1_ID) VALUES (?, ?)

INSERT INTO TABLE_3S (ID, TABLE_2_ID) VALUES (?, ?)

INSERT INTO TABLE_4S (ID, TABLE_3_ID) VALUES (?, ?)

INSERT INTO TABLE_5S (ID, TABLE_4_ID) VALUES (?, ?)