DROP TABLE IF EXISTS TABLE_1S

DROP TABLE IF EXISTS TABLE_2S

DROP TABLE IF EXISTS TABLE_3S

DROP TABLE IF EXISTS TABLE_4S

DROP TABLE IF EXISTS TABLE_5S

CREATE TABLE TABLE_1S (
  ID INT PRIMARY KEY
)

CREATE TABLE TABLE_2S (
  ID INT PRIMARY KEY,
  TABLE_1_ID INT
)

CREATE TABLE TABLE_3S (
  ID INT PRIMARY KEY,
  TABLE_2_ID INT
)

CREATE TABLE TABLE_4S (
  ID INT PRIMARY KEY,
  TABLE_3_ID INT
)

CREATE TABLE TABLE_5S (
  ID INT PRIMARY KEY,
  TABLE_4_ID INT
)

CREATE INDEX IF NOT EXISTS TABLE_1_ID ON TABLE_2S (TABLE_1_ID)

CREATE INDEX IF NOT EXISTS TABLE_2_ID ON TABLE_3S (TABLE_2_ID)

CREATE INDEX IF NOT EXISTS TABLE_3_ID ON TABLE_4S (TABLE_3_ID)

CREATE INDEX IF NOT EXISTS TABLE_4_ID ON TABLE_5S (TABLE_4_ID)
